### ISSUE TITLE
Missing content.

### ISSUE THREAD

**Issue by simucollab** [richardskumat/pubcollab#1]
Your repo is missing content.

Please fix.

**Comment by richardskumat** [comment]
Thank you for the report.

I believe commit https://github.com/richardskumat/pubcollab/commit/71c7bfdd433081333ac26f75ef352e48aae1556a fixes the bug reported.

**Comment by richardskumat** [comment]
This has been achieved in version 1, available from https://github.com/richardskumat/pubcollab/releases/tag/v1.
