### ISSUE TITLE
[Feature Request]Please add PHP code for my IP requests

### ISSUE THREAD

**Issue by richardskumat** [richardskumat/pubcollab#4]
Please add a php file which displays the client's IP on connecting and rendering.

**Comment by simucollab** [comment]
I will add it for version 2.

**Comment by richardskumat** [comment]
Good work! Looks like you've pushed a php file for this! Excellent, thank you!

**Comment by simucollab** [comment]
With the release of v2 at https://github.com/richardskumat/pubcollab/releases/tag/v2, this request has been satisfied.
