### ISSUE TITLE
I want Python to print my name

### ISSUE THREAD

**Issue by simucollab** [richardskumat/pubcollab#5]
I want python now.

**Comment by richardskumat** [comment]
Good idea. I'll see if I can come up with something.

**Comment by simucollab** [comment]
No need for that. I already got that solved.

**Comment by richardskumat** [comment]
Great, then make a pull request.

**Comment by simucollab** [comment]
ETA 2 minutes.

**Comment by richardskumat** [comment]
Pull request https://github.com/richardskumat/pubcollab/pull/6 from you has been merged into this repo's devel branch.

Now onto merging it with master.

**Comment by richardskumat** [comment]
Also will make a v3 tag/release.
